Debra Event/WebClient/WebClient/Pages/AddEvents.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
using System.Text;
using System.Text.Json;

namespace WebClient.Pages
{
    public class AddEventsModel : PageModel
    {

        [BindProperty]
        public Events events { get; set; }
        public async Task<IActionResult> OnPost()//Add Items using post method
        {
            string url = "https://localhost:7202/api/CreateEvent/";
            var content = new StringContent(JsonSerializer.Serialize(events), Encoding.UTF8, "application/json");
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.PostAsync(url, content);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Events");
                else
                    throw new Exception(message.IsSuccessStatusCode.ToString());
            }
        }

    }
}

Debra Event/WebClient/WebClient/Pages/AddItem.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
using System.Text;
using System.Text.Json;

namespace WebClient.Pages
{
    public class AddItemModel : PageModel
    {
        [BindProperty]
        public Items item { get; set; }
        public async Task<IActionResult> OnPost()//Add Items using post method
        {
            string url = "https://localhost:7084/api/Product/" ;
            var content=new StringContent(JsonSerializer.Serialize(item), Encoding.UTF8,"application/json");
            using(HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.PostAsync(url,content);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Items");
                else
                    throw new Exception(message.IsSuccessStatusCode.ToString());
            }
        }
    
    }
}

Debra Event/WebClient/WebClient/Pages/AddTickets.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
using System.Text;
using System.Text.Json;

namespace WebClient.Pages
{
    public class AddTicketsModel : PageModel
    {
        [BindProperty]
        public Tickets tickets { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }

        public async Task<IActionResult> OnPost() // Add Items using post method
        {
            string url = "https://localhost:7202/api/SelTicketControlles/";
            var content = new StringContent(JsonSerializer.Serialize(tickets), Encoding.UTF8, "application/json");
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.PostAsync(url, content);
                if (message.IsSuccessStatusCode)
                {
                    SuccessMessage = "Ticket Sell Successfully";
                    return RedirectToPage("");
                }
                else
                {
                    throw new Exception(message.IsSuccessStatusCode.ToString());
                }
            }
        }
    }
}

Debra Event/WebClient/WebClient/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
using System.Text;
using System.Text.Json;

namespace WebClient.Pages
{
    public class AdminModel : PageModel
    {
        public List<Admin> Admin = new List<Admin>();
        public async Task<IActionResult> OnGet()
        {
            string url = "https://localhost:7202/api/DebraAdmin";
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    Admin = await response.Content.ReadFromJsonAsync<List<Admin>>();
                }
                else
                    throw new Exception(response.StatusCode.ToString());
            }
            return Page();
        }
    }
}

Debra Event/WebClient/WebClient/Pages/AdminLogin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;
using System.Threading.Tasks;
using WebClient.Model;

namespace WebClient.Pages
{
    public class AdminLoginModel : PageModel
    {
        [BindProperty]
        public string AdminEmail { get; set; }

        [BindProperty]
        public string AdminPassword { get; set; }

        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var admin = new Admin
                {
                    AdminEmail = AdminEmail,
                    AdminPassword = AdminPassword
                };

                string url = "https://localhost:7202/api/DebraAdmin/login";
                using (HttpClient client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var json = JsonSerializer.Serialize(admin);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await client.PostAsync(url, content);
                    if (response.IsSuccessStatusCode)
                    {
                        // Handle successful login here, e.g., redirect to the admin dashboard
                        return RedirectToPage("/Option");
                    }
                    else
                    {
                        ErrorMessage = "Invalid email or password.";
                    }
                }
            }
            return Page();
        }

    }
}

Debra Event/WebClient/WebClient/Pages/EditItems.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
using System.Text;
using System.Text.Json;
using Newtonsoft.Json;

namespace WebClient.Pages
{
    public class EditItemsModel : PageModel
    {
        [BindProperty]
        public Items item { get; set; }
        public async Task OnGet(int id)
        {
            string url = "https://localhost:7084/api/Product/" + id;
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var content = await responseMessage.Content.ReadAsStringAsync();
                    item =  JsonConvert.DeserializeObject<Items>(content);
                }
                else
                    throw new Exception(responseMessage.ToString());
            }
            
        }
        public async Task<IActionResult> OnPostUpdate()//Update Button using Onpost update method
        {
            string url = "https://localhost:7084/api/Product/" + item.Id;
            var content = new StringContent(System.Text.Json.JsonSerializer.Serialize(item), Encoding.UTF8, "application/json");
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.PutAsync(url, content);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Items");
                else
                    throw new Exception(message.ToString());
            }
        }
        public async Task<IActionResult> OnPostDelete()//Delete Button using Onpost delete method
        {
            string url = "https://localhost:7084/api/Product/" + item.Id;

            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.DeleteAsync(url);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Items");
                else
                    throw new Exception(message.ToString());
            }
        }
    }
}

Debra Event/WebClient/WebClient/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Debra Event/WebClient/WebClient/Pages/Events.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;

namespace WebClient.Pages
{
    public class EventsModel : PageModel
    {
        public List<Events> Events = new List<Events>();
        public async Task<IActionResult> OnGet()
        {
            string url = "https://localhost:7202/api/CreateEvent";
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    Events = await response.Content.ReadFromJsonAsync<List<Events>>();
                }
                else
                    throw new Exception(response.StatusCode.ToString());
            }
            return Page();
        }
    }
}

Debra Event/WebClient/WebClient/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebClient.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

    }

}

Debra Event/WebClient/WebClient/Pages/Items.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;

namespace WebClient.Pages
{
    public class ItemsModel : PageModel
    {
        public List<Items>Items=new List<Items>();
        public async Task<IActionResult> OnGet()
        {
            string url = "https://localhost:7202/api/Partner";
            using(HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    Items = await response.Content.ReadFromJsonAsync<List<Items>>();
                }
                else
                    throw new Exception(response.StatusCode.ToString());
            }
            return Page();

        }
    }
}

Debra Event/WebClient/WebClient/Pages/ManageEvents.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;
using WebClient.Model;

namespace WebClient.Pages
{
    public class ManageEventsModel : PageModel
    {
        [BindProperty]
        public Events events { get; set; }
        public async Task OnGet(int id)
        {
            string url = "https://localhost:7202/api/CreateEvent/" + id;
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var content = await responseMessage.Content.ReadAsStringAsync();
                    events = JsonConvert.DeserializeObject<Events>(content);
                }
                else
                    throw new Exception(responseMessage.ToString());
            }

        }
        public async Task<IActionResult> OnPostUpdate()//Update Button using Onpost update method
        {
            string url = "https://localhost:7202/api/CreateEvent/" + events.Id;
            var content = new StringContent(System.Text.Json.JsonSerializer.Serialize(events), Encoding.UTF8, "application/json");
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.PutAsync(url, content);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Events");
                else
                    throw new Exception(message.ToString());
            }
        }
        public async Task<IActionResult> OnPostDelete()//Delete Button using Onpost delete method
        {
            string url = "https://localhost:7202/api/CreateEvent/" + events.Id;

            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.DeleteAsync(url);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Events");
                else
                    throw new Exception(message.ToString());
            }
        }
    }
}


       

Debra Event/WebClient/WebClient/Pages/Option.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebClient.Pages
{
    public class OptionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Debra Event/WebClient/WebClient/Pages/PartnerLogin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;
using System.Threading.Tasks;
using WebClient.Model;

namespace WebClient.Pages
{
    public class PartnerLoginModel : PageModel
    {
        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var partner = new Partners
                {
                    Email = Email,
                    Password = Password
                };

                string url = "https://localhost:7202/api/Partner/login";
                using (HttpClient client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var json = JsonSerializer.Serialize(partner);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await client.PostAsync(url, content);
                    if (response.IsSuccessStatusCode)
                    {
                        
                        return RedirectToPage("/Events");
                    }
                    else
                    {
                        ErrorMessage = "Invalid email or password.";
                    }
                }
            }
            return Page();
        }
    }
}

Debra Event/WebClient/WebClient/Pages/Partners.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
namespace WebClient.Pages
{
    public class PartnersModel : PageModel
    {
      
            public List<Partners> Partners = new List<Partners>();
        public async Task<IActionResult> OnGet()
        {
            string url = "https://localhost:7202/api/Partner";
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    Partners = await response.Content.ReadFromJsonAsync<List<Partners>>();
                }
                else
                    throw new Exception(response.StatusCode.ToString());
            }
            return Page();
        }
            }
        
}

Debra Event/WebClient/WebClient/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebClient.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Debra Event/WebClient/WebClient/Pages/RegisterPartner.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebClient.Model;
using System.Text;
using System.Text.Json;
namespace WebClient.Pages
{
    public class RegisterPartnerModel : PageModel
    {
        [BindProperty]
        public Partners partner { get; set; }
        public async Task<IActionResult> OnPost()
        {
            string url = "https://localhost:7202/api/Partner";
            var content = new StringContent(JsonSerializer.Serialize(partner), Encoding.UTF8, "application/json");
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage message = await client.PostAsync(url, content);
                if (message.IsSuccessStatusCode)
                    return RedirectToPage("Partners");
                else
                    throw new Exception(message.IsSuccessStatusCode.ToString());
            }
        }
    }
}

Debra Event/WebClient/WebClient/Pages/AddEvents.cshtml
@page
@model WebClient.Pages.AddEventsModel
@{
}

<form method="post">
    <table>
        <tr>
            <td>Id</td>
            <td><input type="number" readonly asp-for="events.Id"/></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text"asp-for="events.Name"/></td>
        </tr>
         <tr>
            <td>Description</td>
             <td><textarea cols="20" rows="10" asp-for="events.Description"/></textarea></td>
        </tr>
        <tr>
            <td>Location</td>
            <td><input type="text"asp-for="events.Location"/></td>
        </tr>
        <tr>
            <td>Date</td>
            <td><input type="date"asp-for="events.Date"/></td>
        </tr>
        <tr>
            <td>PartnerId</td>
            <td><input type="number"asp-for="events.PartnerId"/></td>
        </tr>
        <tr>
        <td><input type="submit" name="btnAdd"value="Add New"/></td>
             <td></td>
        </tr>
    </table>
</form>

Debra Event/WebClient/WebClient/Pages/AddItem.cshtml
@page
@model WebClient.Pages.AddItemModel
@{
}
<form method="post">
    <table>
        <tr>
            <td>Id</td>
            <td><input type="number" readonly asp-for="item.Id"/></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text"asp-for="item.Name"/></td>
        </tr>
         <tr>
            <td>Price</td>
             <td><input type="numbers"asp-for="item.Price"/></td>
        </tr>
        <tr>
            <td>Stock</td>
             <td><input type="numbers"asp-for="item.Stock"/></td>
        </tr>
         <tr>
            <td>Description</td>
             <td><textarea cols="20" rows="10" asp-for="item.Description"/></textarea></td>
        </tr>
        <tr>
        <td><input type="submit" name="btnAdd"value="Add New"/></td>
             <td></td>
        </tr>
    </table>
</form>

Debra Event/WebClient/WebClient/Pages/Admin.cshtml
@page
@model WebClient.Pages.AdminModel
@{
}
<body>
    <table>
        <tr>
            <th>AdminId</th>
            <th>AdminEmail</th>
            <th>AdminPassword</th>
            <th></th>
        </tr>
        @foreach (var admin in Model.Admin)
        {
                        <tr>
                            <td>@admin.AdminId</td>
                            <td>@admin.AdminEmail</td><span></span>
                            <td>@admin.AdminPassword</td>
                          


                        </tr>
        }
    </table>
</body>

Debra Event/WebClient/WebClient/Pages/AdminLogin.cshtml
@page
@model WebClient.Pages.AdminLoginModel
@{
    ViewData["Title"] = "Admin Login";
}
<style>

    .container {
        background-color: rgb(255, 232, 232);
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        
        margin-top: 60px; 
    }

    h2 {
        font-size: 24px;
        color: #333;
        margin-bottom: 20px;
        text-align: center;
    }

    form div {
        margin-bottom: 15px;
    }

    label {
        display: block;
        font-size: 14px;
        color: #666;
        margin-bottom: 5px;
    }

    input[type="email"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 4px;
        box-sizing: border-box;
        font-size: 14px;
    }

    button {
            background-color: palevioletred;
        color: #fff;
        border: none;
        padding: 10px 15px;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        width: 100%;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    p {
        color: red;
        font-size: 14px;
        text-align: center;
    }
</style>

<div>
    <h2>Admin Login</h2>

<form method="post">
    <div>
        <label for="AdminEmail">Email:</label>
        <input type="email" id="AdminEmail" name="AdminEmail" asp-for="AdminEmail" required />
    </div>
    <div>
        <label for="AdminPassword">Password:</label>
        <input type="password" id="AdminPassword" name="AdminPassword" asp-for="AdminPassword" required />
    </div>
    <button type="submit">Login</button>
</form>

</div>
@if (Model.ErrorMessage != null)
{
    <p style="color:red;">@Model.ErrorMessage</p>
}

Debra Event/WebClient/WebClient/Pages/EditItems.cshtml
@page
@model WebClient.Pages.EditItemsModel
@{
}

<form method="post">
    <table>
        <tr>
            <td>Id</td>
            <td><input type="number" readonly asp-for="item.Id"/></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text"asp-for="item.Name"/></td>
        </tr>
         <tr>
            <td>Price</td>
             <td><input type="numbers"asp-for="item.Price"/></td>
        </tr>
        <tr>
            <td>Stock</td>
             <td><input type="numbers"asp-for="item.Stock"/></td>
        </tr>
         <tr>
            <td>Description</td>
             <td><textarea cols="20" rows="10" asp-for="item.Description"/></textarea></td>
        </tr>
        <tr>
        <td><input type="submit" name="btnUpdate"value="Update" asp-page-handler="Update"/></td>
             <td><input type="submit" id="btnDelete"value="Delete"asp-page-handler="Delete"/></td>
        </tr>
    </table>
</form>

Debra Event/WebClient/WebClient/Pages/Events.cshtml
@page
@model WebClient.Pages.EventsModel
@{
}
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<style>
      body {
        padding: 20px;
        font-family: Arial, sans-serif;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
        color: black;
    }

    tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    tr:hover {
        background-color: #ddd;
    }

    button a {
        color: white;
        text-decoration: none;
    }

    button {
        background-color: #45a049;
        border: none;
        color: white;
        padding: 5px 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 5px;
    }

    button:hover {
         background-color: #0056b3; 
        color:white;


    }

    button:hover a{
        color:white;
        text-decoration: none;
    }
</style>
<body>
    
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Location</th>
            <th>Date</th>
             <th>Process</th>
            <th></th>
        </tr>
        @foreach (var events in Model.Events)
        {
                    <tr>
                                <td>@events.Id</td>
                                <td>@events.Name</td>
                                <td>@events.Description</td>
                                <td>@events.Location</td>
                                <td>@events.Date</td>
                                    <td> <button><a href="/AddTickets">Buy Ticket</a></button></td>

                        

                    </tr>
        }
    </table>
</body>

Debra Event/WebClient/WebClient/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Debra Event</title>
    <style>
        .text-center {
            background-color: rgb(255, 232, 232);
               /*background-image: url(img/234.PNG);
             background-size: cover;*/
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 80vh; 
            text-align: center;
            padding-down:50px;
        }
        .text-center h1 {
            font-size: 25px;
            font-weight: bold;

        }
        .text-center button {
            color: black;
            background-color: palevioletred;
            box-shadow: white;
            font-size: 25px;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            border-radius: 25px;
        }
        .text-center button:hover{
            background-color:aqua;
        }
        .text-center button a {
            text-decoration: none;
            color: black;
            font-weight: bold;
            font-size: 20px;
        }

        /* Page Navbar */
        nav {
            background: #ca60c5;
            padding: 0 20px;
        }

        .nav-container {
            list-style: none;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .logo-container {
            flex: 0 0 auto;
        }

        .logo {
            color: aliceblue;
            padding: 20px;
            font-size: 30px;
        }

        .logo span {
            color: rgb(255, 166, 0);
        }

        .navbar {
            display: flex;
            justify-content: flex-end;
            flex: 1;
        }

        .navbar li {
            position: relative;
        }

        .navbar li a {
            display: block;
            padding: 20px 25px;
            color: aliceblue;
            text-decoration: none;
            text-align: center;
            font-size: 20px;
        }

        .navbar li a:hover, .navbar li:hover > a {
            background: rgb(22, 122, 142);
            color: orange;
        }

        .navbar li:hover ul.dropdown {
            display: block;
        }
    </style>
</head>
<body>
    <nav>
        <ul class="nav-container">
            <li class="logo-container">
                <h1 class="logo">Debra <span>Events</span></h1>
            </li>
            <div class="navbar">
                <li><a href="home.html">Home</a></li>
                <li><a href="gallery.html">Privacy</a></li>
                <li><a href="#about_us_container">Help</a></li>
            </div>
        </ul>
    </nav>

    <div class="text-center">
        <h1 class="display-4">Welcome To Debra Event Management</h1>
        <button><a href="/PartnerLogin">User Login</a></button>
    </div>
</body>
</html>

Debra Event/WebClient/WebClient/Pages/Items.cshtml
@page
@model WebClient.Pages.ItemsModel
@{
}
<body>
    <a asp-page="AddItem">Add New</a>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Stock</th>
            <th></th>
        </tr>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Price</td>
                <td>@item.Stock</td>
                <td>
                    <a asp-page="EditItems"asp-route-id="@item.Id">Edit</a>
                </td>
                
               
            </tr>
        }
    </table>
</body>

Debra Event/WebClient/WebClient/Pages/ManageEvents.cshtml
@page
@model WebClient.Pages.ManageEventsModel
@{
}
<table>
         <tr>
            <td>Id</td>
            <td><input type="number" readonly asp-for="events.Id"/></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text"asp-for="events.Name"/></td>
        </tr>
         <tr>
            <td>Description</td>
             <td><textarea cols="20" rows="10" asp-for="events.Description"/></textarea></td>
        </tr>
        <tr>
            <td>Location</td>
            <td><input type="text"asp-for="events.Location"/></td>
        </tr>
        <tr>
            <td>Date</td>
            <td><input type="date"asp-for="events.Date"/></td>
        </tr>
        <tr>
            <td>PartnerId</td>
            <td><input type="number"asp-for="events.PartnerId"/></td>
        </tr>
        <td><input type="submit" name="btnUpdate"value="Update" asp-page-handler="Update"/></td>
             <td><input type="submit" id="btnDelete"value="Delete"asp-page-handler="Delete"/></td>
        </tr>
    </table>

Debra Event/WebClient/WebClient/Pages/Option.cshtml
@page
@model WebClient.Pages.OptionModel
@{
}

<style>
* {
    background-color: rgb(212, 202, 202);
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

.center-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.button-container {
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin-top: 20px;
}

.button-container a {
    text-decoration: none;
    color: inherit;
    font-weight: bold;
    display: block;
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    border-radius: 20px;
    background-color: rgb(85, 117, 126);
    text-align: center;
    border: none; 
    box-shadow: none; 
}

.button-container a:hover {
    background-color: palevioletred;
    border: none; 
    box-shadow: none; 
}



</style>

<div class="center-container">
    <h2>Admin Management Center</h2>
    <div class="button-container">
        <button><a href="/Partners">View PartnerDetails</a></button>
        <button><a href="/Events">View EventDetails</a></button>
        <button><a href="/Tickets">View TicketsDetails</a></button>
        <button><a href="/Admin">View AdminDetails</a></button>
    </div>
</div>